/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.stream.Stream;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

class LibraryTest {

    @ParameterizedTest
    @MethodSource(value = "examples")
    void someLibraryMethodReturnsTrue(String example) {
        assertNotNull(example);
    }

    public static Stream<String> examples() throws Exception {
        var path = Paths.get(LibraryTest.class.getClassLoader().getResource("examples").toURI());

        try (var walk = Files.walk(path)) {
            return walk
                // uncomment to make the test pass
                // .toList().stream()
                .map(file -> file.getFileName().toString());
        }
    }
}
